// src/main/webapp/app/entities/room/room-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IReservation } from 'app/shared/model/reservation.model';
import { getEntities as getReservations } from 'app/entities/reservation/reservation.reducer';
import { getEntity, updateEntity, createEntity, reset } from './room.reducer';
import { IRoom } from 'app/shared/model/room.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IRoomUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IRoomUpdateState {
  isNew: boolean;
  reservationId: string;
}

export class RoomUpdate extends React.Component<IRoomUpdateProps, IRoomUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      reservationId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getReservations();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { roomEntity } = this.props;
      const entity = {
        ...roomEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
      this.handleClose();
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/room');
  };

  render() {
    const { roomEntity, reservations, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="mainApp.room.home.createOrEditLabel">
              <Translate contentKey="mainApp.room.home.createOrEditLabel">Create or edit a Room</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : roomEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="room-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="roomNumberLabel" for="roomNumber">
                    <Translate contentKey="mainApp.room.roomNumber">Room Number</Translate>
                  </Label>
                  <AvField
                    id="room-roomNumber"
                    type="string"
                    className="form-control"
                    name="roomNumber"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      min: { value: 1, errorMessage: translate('entity.validation.min', { min: 1 }) },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="roomTypeLabel">
                    <Translate contentKey="mainApp.room.roomType">Room Type</Translate>
                  </Label>
                  <AvInput
                    id="room-roomType"
                    type="select"
                    className="form-control"
                    name="roomType"
                    value={(!isNew && roomEntity.roomType) || 'STANDARD'}
                  >
                    <option value="STANDARD">
                      <Translate contentKey="mainApp.RoomType.STANDARD" />
                    </option>
                    <option value="COMFORT">
                      <Translate contentKey="mainApp.RoomType.COMFORT" />
                    </option>
                    <option value="LUXE">
                      <Translate contentKey="mainApp.RoomType.LUXE" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label id="floorLabel" for="floor">
                    <Translate contentKey="mainApp.room.floor">Floor</Translate>
                  </Label>
                  <AvField
                    id="room-floor"
                    type="string"
                    className="form-control"
                    name="floor"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      min: { value: 0, errorMessage: translate('entity.validation.min', { min: 0 }) },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/room" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  reservations: storeState.reservation.entities,
  roomEntity: storeState.room.entity,
  loading: storeState.room.loading,
  updating: storeState.room.updating
});

const mapDispatchToProps = {
  getReservations,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(RoomUpdate);

// src/main/webapp/app/entities/room/room-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IRoom, Room } from 'app/shared/model/room.model';
import { RoomService } from './room.service';

@Component({
  selector: 'jhi-room-update',
  templateUrl: './room-update.component.html'
})
export class RoomUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    roomNumber: [null, [Validators.required, Validators.min(1)]],
    roomType: [],
    floor: [null, [Validators.required, Validators.min(0)]]
  });

  constructor(protected roomService: RoomService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ room }) => {
      this.updateForm(room);
    });
  }

  updateForm(room: IRoom): void {
    this.editForm.patchValue({
      id: room.id,
      roomNumber: room.roomNumber,
      roomType: room.roomType,
      floor: room.floor
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const room = this.createFromForm();
    if (room.id !== undefined) {
      this.subscribeToSaveResponse(this.roomService.update(room));
    } else {
      this.subscribeToSaveResponse(this.roomService.create(room));
    }
  }

  private createFromForm(): IRoom {
    return {
      ...new Room(),
      id: this.editForm.get(['id'])!.value,
      roomNumber: this.editForm.get(['roomNumber'])!.value,
      roomType: this.editForm.get(['roomType'])!.value,
      floor: this.editForm.get(['floor'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IRoom>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-room-heading" jhiTranslate="mainApp.room.home.createOrEditLabel">Create or edit a Room</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mainApp.room.roomNumber" for="field_roomNumber">Room Number</label>
                    <input type="number" class="form-control" name="roomNumber" id="field_roomNumber"
                           formControlName="roomNumber"/>
                    <div *ngIf="editForm.get('roomNumber')!.invalid && (editForm.get('roomNumber')!.dirty || editForm.get('roomNumber')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('roomNumber')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('roomNumber')?.errors?.min" jhiTranslate="entity.validation.min" [translateValues]="{ min: 1 }">
                            This field should be at least 1.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('roomNumber')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mainApp.room.roomType" for="field_roomType">Room Type</label>
                    <select class="form-control" name="roomType" formControlName="roomType" id="field_roomType">
                        <option value="STANDARD">{{ 'mainApp.RoomType.STANDARD' | translate }}</option>
                        <option value="COMFORT">{{ 'mainApp.RoomType.COMFORT' | translate }}</option>
                        <option value="LUXE">{{ 'mainApp.RoomType.LUXE' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="mainApp.room.floor" for="field_floor">Floor</label>
                    <input type="number" class="form-control" name="floor" id="field_floor"
                           formControlName="floor"/>
                    <div *ngIf="editForm.get('floor')!.invalid && (editForm.get('floor')!.dirty || editForm.get('floor')!.touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('floor')?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('floor')?.errors?.min" jhiTranslate="entity.validation.min" [translateValues]="{ min: 0 }">
                            This field should be at least 0.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('floor')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
