// src/main/webapp/app/entities/room/room.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IRoom } from 'app/shared/model/room.model';
import { RoomService } from './room.service';
import { RoomDeleteDialogComponent } from './room-delete-dialog.component';

@Component({
  selector: 'jhi-room',
  templateUrl: './room.component.html'
})
export class RoomComponent implements OnInit, OnDestroy {
  rooms?: IRoom[];
  eventSubscriber?: Subscription;

  constructor(protected roomService: RoomService, protected eventManager: JhiEventManager, protected modalService: NgbModal) {}

  loadAll(): void {
    this.roomService.query().subscribe((res: HttpResponse<IRoom[]>) => (this.rooms = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInRooms();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IRoom): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInRooms(): void {
    this.eventSubscriber = this.eventManager.subscribe('roomListModification', () => this.loadAll());
  }

  delete(room: IRoom): void {
    const modalRef = this.modalService.open(RoomDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.room = room;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="mainApp.room.home.title">Rooms</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-room" [routerLink]="['/room/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="mainApp.room.home.createLabel">
            Create a new Room
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="rooms?.length === 0">
        <span jhiTranslate="mainApp.room.home.notFound">No rooms found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="rooms && rooms.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="mainApp.room.roomNumber">Room Number</span></th>
                    <th scope="col" ><span jhiTranslate="mainApp.room.roomType">Room Type</span></th>
                    <th scope="col" ><span jhiTranslate="mainApp.room.floor">Floor</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let room of rooms ;trackBy: trackId">
                    <td><a [routerLink]="['/room', room.id, 'view']">{{ room.id }}</a></td>
                    <td>{{ room.roomNumber }}</td>
                    <td jhiTranslate="{{ 'mainApp.RoomType.' + room.roomType }}">{{ room.roomType }}</td>
                    <td>{{ room.floor }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/room', room.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/room', room.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(room)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/room/room.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './room.reducer';
import { IRoom } from 'app/shared/model/room.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IRoomProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Room extends React.Component<IRoomProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { roomList, match } = this.props;
    return (
      <div>
        <h2 id="room-heading">
          <Translate contentKey="mainApp.room.home.title">Rooms</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="mainApp.room.home.createLabel">Create new Room</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          {roomList && roomList.length > 0 ? (
            <Table responsive>
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="mainApp.room.roomNumber">Room Number</Translate>
                  </th>
                  <th>
                    <Translate contentKey="mainApp.room.roomType">Room Type</Translate>
                  </th>
                  <th>
                    <Translate contentKey="mainApp.room.floor">Floor</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {roomList.map((room, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${room.id}`} color="link" size="sm">
                        {room.id}
                      </Button>
                    </td>
                    <td>{room.roomNumber}</td>
                    <td>
                      <Translate contentKey={`mainApp.RoomType.${room.roomType}`} />
                    </td>
                    <td>{room.floor}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${room.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${room.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${room.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="mainApp.room.home.notFound">No Rooms found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ room }: IRootState) => ({
  roomList: room.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Room);
