// src/main/webapp/app/entities/guest/guest.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './guest.reducer';
import { IGuest } from 'app/shared/model/guest.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IGuestProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export class Guest extends React.Component<IGuestProps> {
  componentDidMount() {
    this.props.getEntities();
  }

  render() {
    const { guestList, match } = this.props;
    return (
      <div>
        <h2 id="guest-heading">
          <Translate contentKey="mainApp.guest.home.title">Guests</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="mainApp.guest.home.createLabel">Create new Guest</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          {guestList && guestList.length > 0 ? (
            <Table responsive>
              <thead>
                <tr>
                  <th>
                    <Translate contentKey="global.field.id">ID</Translate>
                  </th>
                  <th>
                    <Translate contentKey="mainApp.guest.name">Name</Translate>
                  </th>
                  <th>
                    <Translate contentKey="mainApp.guest.phone">Phone</Translate>
                  </th>
                  <th>
                    <Translate contentKey="mainApp.guest.email">Email</Translate>
                  </th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {guestList.map((guest, i) => (
                  <tr key={`entity-${i}`}>
                    <td>
                      <Button tag={Link} to={`${match.url}/${guest.id}`} color="link" size="sm">
                        {guest.id}
                      </Button>
                    </td>
                    <td>{guest.name}</td>
                    <td>{guest.phone}</td>
                    <td>{guest.email}</td>
                    <td className="text-right">
                      <div className="btn-group flex-btn-group-container">
                        <Button tag={Link} to={`${match.url}/${guest.id}`} color="info" size="sm">
                          <FontAwesomeIcon icon="eye" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.view">View</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${guest.id}/edit`} color="primary" size="sm">
                          <FontAwesomeIcon icon="pencil-alt" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.edit">Edit</Translate>
                          </span>
                        </Button>
                        <Button tag={Link} to={`${match.url}/${guest.id}/delete`} color="danger" size="sm">
                          <FontAwesomeIcon icon="trash" />{' '}
                          <span className="d-none d-md-inline">
                            <Translate contentKey="entity.action.delete">Delete</Translate>
                          </span>
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          ) : (
            <div className="alert alert-warning">
              <Translate contentKey="mainApp.guest.home.notFound">No Guests found</Translate>
            </div>
          )}
        </div>
      </div>
    );
  }
}

const mapStateToProps = ({ guest }: IRootState) => ({
  guestList: guest.entities
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Guest);

// src/main/webapp/app/entities/guest/guest.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IGuest } from 'app/shared/model/guest.model';
import { GuestService } from './guest.service';
import { GuestDeleteDialogComponent } from './guest-delete-dialog.component';

@Component({
  selector: 'jhi-guest',
  templateUrl: './guest.component.html'
})
export class GuestComponent implements OnInit, OnDestroy {
  guests?: IGuest[];
  eventSubscriber?: Subscription;

  constructor(protected guestService: GuestService, protected eventManager: JhiEventManager, protected modalService: NgbModal) {}

  loadAll(): void {
    this.guestService.query().subscribe((res: HttpResponse<IGuest[]>) => (this.guests = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInGuests();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IGuest): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInGuests(): void {
    this.eventSubscriber = this.eventManager.subscribe('guestListModification', () => this.loadAll());
  }

  delete(guest: IGuest): void {
    const modalRef = this.modalService.open(GuestDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.guest = guest;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="mainApp.guest.home.title">Guests</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-guest" [routerLink]="['/guest/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="mainApp.guest.home.createLabel">
            Create a new Guest
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="guests?.length === 0">
        <span jhiTranslate="mainApp.guest.home.notFound">No guests found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="guests?.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="mainApp.guest.name">Name</span></th>
                    <th scope="col" ><span jhiTranslate="mainApp.guest.phone">Phone</span></th>
                    <th scope="col" ><span jhiTranslate="mainApp.guest.email">Email</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let guest of guests ;trackBy: trackId">
                    <td><a [routerLink]="['/guest', guest.id, 'view']">{{ guest.id }}</a></td>
                    <td>{{ guest.name }}</td>
                    <td>{{ guest.phone }}</td>
                    <td>{{ guest.email }}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/guest', guest.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/guest', guest.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(guest)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
